In [3]:
import torch
from sentence_transformers import SentenceTransformer
import pandas as pd
import numpy as np
import ast
from sklearn.metrics.pairwise import cosine_similarity

In [4]:
df = pd.read_csv("../DataSets/processed/courses_content_based_data_after_eda_after_embedding.csv",sep=";")

In [5]:
df.head()

,id,all_course_descriptions,all_degree_descriptions,all_degree_names,all_stream_names,all_course_names,combined_text,embeddings
0,1,Accounting and Finance,Bachelor of Commerce (BCom) degree with a focu...,Bachelor of Commerce,B.Com,Commerce,Accounting and Finance Bachelor of Commerce (B...,"0.032680117,-0.0068294355,-0.03761506,0.012504..."
1,1,Biochemistry,Bachelor of Science (BSc) in Biochemistry prov...,Bachelor of Science (3years) - B.Sc,B.Sc,Science,Biochemistry Bachelor of Science (BSc) in Bioc...,"0.0016461394,-0.04510996,-0.0051856474,-0.0386..."
2,1,Business Administration,Bachelor of Business Administration (BBA) in B...,Bachelor of Business Administration,BBA,Management,Business Administration Bachelor of Business A...,"-0.001190734,0.0020734745,-0.0679722,0.0215501..."
3,1,Computer Applications,Bachelor of Commerce (BCom) program with a spe...,"Bachelor of Commerce, Bachelor of Computer App...","B.Com, BCA","Commerce, Science",Computer Applications Bachelor of Commerce (BC...,"-0.02175461,0.020506347,-0.021652596,-0.079396..."
4,1,Computer Science,Bachelor of Science (BSc) in Computer Science ...,Bachelor of Science (3years) - B.Sc,B.Sc,Science,Computer Science Bachelor of Science (BSc) in ...,"-0.066155404,0.035149444,-0.03656299,-0.034421..."

Load model

In [6]:
model = SentenceTransformer("all-MiniLM-L6-v2")

In [10]:
df.head()

,id,all_course_descriptions,all_degree_descriptions,all_degree_names,all_stream_names,all_course_names,combined_text,embeddings
0,1,Accounting and Finance,Bachelor of Commerce (BCom) degree with a focu...,Bachelor of Commerce,B.Com,Commerce,Accounting and Finance Bachelor of Commerce (B...,"0.032680117,-0.0068294355,-0.03761506,0.012504..."
1,1,Biochemistry,Bachelor of Science (BSc) in Biochemistry prov...,Bachelor of Science (3years) - B.Sc,B.Sc,Science,Biochemistry Bachelor of Science (BSc) in Bioc...,"0.0016461394,-0.04510996,-0.0051856474,-0.0386..."
2,1,Business Administration,Bachelor of Business Administration (BBA) in B...,Bachelor of Business Administration,BBA,Management,Business Administration Bachelor of Business A...,"-0.001190734,0.0020734745,-0.0679722,0.0215501..."
3,1,Computer Applications,Bachelor of Commerce (BCom) program with a spe...,"Bachelor of Commerce, Bachelor of Computer App...","B.Com, BCA","Commerce, Science",Computer Applications Bachelor of Commerce (BC...,"-0.02175461,0.020506347,-0.021652596,-0.079396..."
4,1,Computer Science,Bachelor of Science (BSc) in Computer Science ...,Bachelor of Science (3years) - B.Sc,B.Sc,Science,Computer Science Bachelor of Science (BSc) in ...,"-0.066155404,0.035149444,-0.03656299,-0.034421..."

In [ ]:
# df.columns = ["id","course_name", "course_description","degree_description","degree_name","stream_name", "similarity"]

In [7]:
def recommend_courses(input_text, top_n=5):
    input_embedding = model.encode([input_text])

    df["similarity"] = df["embeddings"].apply(lambda x: cosine_similarity([x], input_embedding)[0][0])

    recommendations = df.sort_values(by="similarity", ascending=False).head(top_n)

    return recommendations

In [8]:
index = eval(input())
input_text = df["combined_text"].iloc[index]
print(f"User Searched for : {df["course_names"].iloc[index]}")
recommended_courses = recommend_courses(input_text)
recommended_courses

KeyError: 'course_name'

In [9]:
df.head()

,id,all_course_descriptions,all_degree_descriptions,all_degree_names,all_stream_names,all_course_names,combined_text,embeddings
0,1,Accounting and Finance,Bachelor of Commerce (BCom) degree with a focu...,Bachelor of Commerce,B.Com,Commerce,Accounting and Finance Bachelor of Commerce (B...,"0.032680117,-0.0068294355,-0.03761506,0.012504..."
1,1,Biochemistry,Bachelor of Science (BSc) in Biochemistry prov...,Bachelor of Science (3years) - B.Sc,B.Sc,Science,Biochemistry Bachelor of Science (BSc) in Bioc...,"0.0016461394,-0.04510996,-0.0051856474,-0.0386..."
2,1,Business Administration,Bachelor of Business Administration (BBA) in B...,Bachelor of Business Administration,BBA,Management,Business Administration Bachelor of Business A...,"-0.001190734,0.0020734745,-0.0679722,0.0215501..."
3,1,Computer Applications,Bachelor of Commerce (BCom) program with a spe...,"Bachelor of Commerce, Bachelor of Computer App...","B.Com, BCA","Commerce, Science",Computer Applications Bachelor of Commerce (BC...,"-0.02175461,0.020506347,-0.021652596,-0.079396..."
4,1,Computer Science,Bachelor of Science (BSc) in Computer Science ...,Bachelor of Science (3years) - B.Sc,B.Sc,Science,Computer Science Bachelor of Science (BSc) in ...,"-0.066155404,0.035149444,-0.03656299,-0.034421..."